### PR TITLE
Update package version to 1.3.0

### PR DESCRIPTION
**Pull request by MadhukaHarith92**
## Checklist
- [ ] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests
- [ ] Updated the spec

### CODE REVIEW

**Review by niveathika — COMMENTED** [review]
Lets update the changelog

**Comment by MadhukaHarith92** [comment]
> Lets update the changelog

Changelog already has the info of the new APIs: https://github.com/ballerina-platform/module-ballerina-os/blob/master/changelog.md

**Comment by niveathika** [comment]
Changelog has only 2 entries. Are these going both for 1.3.0? What about lower versions, didn't we maintain the changes?

**Comment by MadhukaHarith92** [comment]
> Changelog has only 2 entries. Are these going both for 1.3.0? What about lower versions, didn't we maintain the changes?

Yes, both are going with 1.3.0. These are the first and only API changes in the OS module since the Changelog was created.

**Review by daneshk — APPROVED** [review]

**Pull request merged**
